spring.application.name=ITQUIZ
spring.datasource.url=jdbc:postgresql://localhost:5432/itquiz
spring.datasource.username=postgres
spring.datasource.password=lahcen2025
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true